version: '3.8'

services:

  web:
    container_name: cdash-web
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    container_name: cdash-db
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db

  chrome:
    container_name: cdash-chrome
    image: selenium/standalone-chrome:latest
    hostname: chrome
    privileged: true
    shm_size: 2g
    depends_on:
      - db

  crawler:
    container_name: cdash-crawler
    build: ./services/crawler
    command: python project/app.py
    volumes:
      - ./services/crawler/:/usr/src/app/
    depends_on:
      - db
      - chrome
    env_file:
      - ./.env.dev

  notifier:
    container_name: cdash-notifier
    build: ./services/notifier
    volumes:
      - ./services/notifier/:/usr/src/app/
    depends_on:
      - db
    env_file:
      - ./.env.dev.notifier

volumes:
  postgres_data:
