version: '3.8'

services:

  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db

  crawler:
    build: ./services/crawler
    command: python project/app.py
    volumes:
      - ./services/crawler/:/usr/src/app/
    depends_on:
      - db
    env_file:
      - ./.env.dev

volumes:
  postgres_data:
